# -*- coding: utf-8 -*-

gdelt_1_colnames = ["GLOBALEVENTID",
                    "SQLDATE",
                    "MonthYear",
                    "Year",
                    "FractionDate",
                    "Actor1Code",
                    "Actor1Name",
                    "Actor1CountryCode",
                    "Actor1KnownGroupCode",
                    "Actor1EthnicCode",
                    "Actor1Religion1Code",
                    "Actor1Religion2Code",
                    "Actor1Type1Code",
                    "Actor1Type2Code",
                    "Actor1Type3Code",
                    "Actor2Code",
                    "Actor2Name",
                    "Actor2CountryCode",
                    "Actor2KnownGroupCode",
                    "Actor2EthnicCode",
                    "Actor2Religion1Code",
                    "Actor2Religion2Code",
                    "Actor2Type1Code",
                    "Actor2Type2Code",
                    "Actor2Type3Code",
                    "IsRootEvent",
                    "EventCode",
                    "EventBaseCode",
                    "EventRootCode",
                    "QuadClass",
                    "GoldsteinScale",
                    "NumMentions",
                    "NumSources",
                    "NumArticles",
                    "AvgTone",
                    "Actor1Geo_Type",
                    "Actor1Geo_FullName",
                    "Actor1Geo_CountryCode",
                    "Actor1Geo_ADM1Code",
                    "Actor1Geo_Lat",
                    "Actor1Geo_Long",
                    "Actor1Geo_FeatureID",
                    "Actor2Geo_Type",
                    "Actor2Geo_FullName",
                    "Actor2Geo_CountryCode",
                    "Actor2Geo_ADM1Code",
                    "Actor2Geo_Lat",
                    "Actor2Geo_Long",
                    "Actor2Geo_FeatureID",
                    "ActionGeo_Type",
                    "ActionGeo_FullName",
                    "ActionGeo_CountryCode",
                    "ActionGeo_ADM1Code",
                    "ActionGeo_Lat",
                    "ActionGeo_Long",
                    "ActionGeo_FeatureID",
                    "DATEADDED",
                    "SOURCEURL"]

gdelt_1_colnames_old = ["GLOBALEVENTID",
                        "SQLDATE",
                        "MonthYear",
                        "Year",
                        "FractionDate",
                        "Actor1Code",
                        "Actor1Name",
                        "Actor1CountryCode",
                        "Actor1KnownGroupCode",
                        "Actor1EthnicCode",
                        "Actor1Religion1Code",
                        "Actor1Religion2Code",
                        "Actor1Type1Code",
                        "Actor1Type2Code",
                        "Actor1Type3Code",
                        'Actor2Code',
                        "Actor2Name",
                        "Actor2CountryCode",
                        "Actor2KnownGroupCode",
                        "Actor2EthnicCode",
                        "Actor2Religion1Code",
                        "Actor2Religion2Code",
                        "Actor2Type1Code",
                        "Actor2Type2Code",
                        "Actor2Type3Code",
                        "IsRootEvent",
                        "EventCode",
                        "EventBaseCode",
                        "EventRootCode",
                        "QuadClass",
                        "GoldsteinScale",
                        "NumMentions",
                        "NumSources",
                        "NumArticles",
                        "AvgTone",
                        "Actor1Geo_Type",
                        "Actor1Geo_FullName",
                        "Actor1Geo_CountryCode",
                        "Actor1Geo_ADM1Code",
                        "Actor1Geo_Lat",
                        "Actor1Geo_Long",
                        "Actor1Geo_FeatureID",
                        "Actor2Geo_Type",
                        "Actor2Geo_FullName",
                        "Actor2Geo_CountryCode",
                        "Actor2Geo_ADM1Code",
                        "Actor2Geo_Lat",
                        "Actor2Geo_Long",
                        "Actor2Geo_FeatureID",
                        "ActionGeo_Type",
                        "ActionGeo_FullName",
                        "ActionGeo_CountryCode",
                        "ActionGeo_ADM1Code",
                        "ActionGeo_Lat",
                        "ActionGeo_Long",
                        "ActionGeo_FeatureID",
                        "DATEADDED",
                        ]

AFRICAN_COUNTRIES = ["Algeria",
                     "Angola",
                     "Benin",
                     "Botswana",
                     "Burkina Faso",
                     "Burundi",
                     "Cameroon",
                     "Central African Republic",
                     "Chad",
                     "Democratic Republic of Congo",
                     "Djibouti",
                     "Egypt",
                     "Equitorial Guinea",
                     "Eritrea",
                     "Ethiopia",
                     "Gabon",
                     "Gambia",
                     "Ghana",
                     "Guinea",
                     "Guinea-Bissou",
                     "Ivory Coast",
                     "Kenya",
                     "Lesotho",
                     "Liberia",
                     "Libya",
                     "Madagascar",
                     "Malawi",
                     "Mali",
                     "Mauritania",
                     "Morocco",
                     "Mozambique",
                     "Namibia",
                     "Niger",
                     "Nigeria",
                     "Republic of Congo",
                     "Rwanda",
                     "Senegal",
                     "Sierra Leone",
                     "Somalia",
                     "South Africa",
                     "South Sudan",
                     "Sudan",
                     "Swaziland",
                     "Tanzania",
                     "Togo",
                     "Tunisia",
                     "Uganda",
                     "Zambia",
                     "Zimbabwe"
                     ]

WEST_AFRICAN_COUNTRIES = [
    "Algeria",
    "Benin",
    "Burkina Faso",
    "Cameroon",
    "Chad",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Ivory Coast",
    "Liberia",
    "Libya",
    "Mali",
    "Mauritania",
    "Morocco",
    "Niger",
    "Nigeria",
    "Senegal",
    "Sierra Leone",
    "Togo",
]

CONFLICT_CAMEO_BASE_CODES = ("17", "18", "19", "20")
